AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/Attr:
  Exclude:
    - 'app/graphql/**/*'
